version: '3.8'

services:
  app:
    build: .
    container_name: poc-tasy
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run start:dev